### Get by name

GET http://localhost:3000/players?sortCol=name&sortOrder=asc&limit=5&offset=0


### Get by jersey
GET http://localhost:3000/players?sortCol=jersey&sortOrder=asc&limit=5&offset=0


### Get by position
GET http://localhost:3000/players?sortCol=position&sortOrder=asc&limit=5&offset=0


### Get by team
GET http://localhost:3000/players?sortCol=team&sortOrder=asc&limit=5&offset=0&q=a


### Get by team and search
GET http://localhost:3000/players?sortCol=name&sortOrder=asc&limit=100&offset=0

### POST a player
POST http://localhost:3000/addPlayers
Content-Type: application/json; charset=utf-8

{
      "name": "aliss",
      "jersey": 200,
      "position": "Goalie",
      "team": "Edmonton Oilers"
}

### check validator
POST http://localhost:3000/addPlayers
Content-Type: application/json; charset=utf-8

{
      "name": "alii",
      "jersey": 12 ,
      "position": "Goalie",
      "team": "torento"
}


### delete a player
DELETE http://localhost:3000/deletePlayer/55